Tarea 5 Completa
Cursos-Automatizacion-Pruebas/Tarea5 pull request #2
Opened 2022-06-28 01:57 UTC by juandedios199012

Curso Abril -  Mayo
Tarea 5 Completa
Para su revision

2022-06-28 02:01 UTC, calvarioTeacher31 requested changes

2022-06-28 02:01 UTC, calvarioTeacher31 commented on src/test/java/RemoveElementsTests.java
> +            addElementBoton.click();
por qué un for y no un foreach?

2022-06-28 02:01 UTC, calvarioTeacher31 commented on src/test/java/RemoveElementsTests.java
> +        for (int i=0; i<deleteBotonLista.size();i++) {
por qué un for y no un foreach?

2022-06-28 02:01 UTC, calvarioTeacher31 commented on src/test/java/RemoveElementsTests.java
>      public void theInternetAddRemoveElementsTest() throws InterruptedException {
quitar  throws InterruptedException y poner un try catch en el thread sleep

2022-06-28 03:34 UTC, calvarioTeacher31 commented on src/test/java/RemoveElementsTests.java
>          for (int i = 0; i < 10; i++) {
por qué un for y no un foreach?

2022-06-28 18:27 UTC, calvarioTeacher31 commented on src/test/java/RemoveElementsTests.java
>          }
como extra puedes agregar la verificacion que efectivamente ya los botones delete no están

2022-06-28 18:29 UTC, calvarioTeacher31 approved these changes

2022-07-04 03:06 UTC, juandedios199012 commented
merge

2022-07-04 03:06 UTC, merged